# app.yaml
runtime: nodejs16

instance_class: F2

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  max_instances: 3
  target_cpu_utilization: 0.65

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /(.*\.(json|ico|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(json|ico|png|jpg)$
    secure: always

  - url: /.*
    script: auto
    secure: always
